### ISSUE TITLE
PDL-LinearAlgebra-0.37 fails install for Strawberry perl5 (revision 5 version 32 subversion 1)

### ISSUE THREAD

**Issue by offtob** [PDLPorters/pdl-linearalgebra#23]
Below is the install output 
[build.log](https://github.com/PDLPorters/pdl/files/11415723/build.log)

```
PS C:\Users\Shahriar> cpanm -i --force PDL::LinearAlgebra
--> Working on PDL::LinearAlgebra
Fetching http://www.cpan.org/authors/id/E/ET/ETJ/PDL-LinearAlgebra-0.37.tar.gz ... OK
Configuring PDL-LinearAlgebra-0.37 ... OK
cpanm : ! Installing PDL::LinearAlgebra failed. See E:\Sha\.cpanm\work\1683481359.16780\build.log for details. Retry with --force to force install it.
At line:1 char:1
+ cpanm -i --force PDL::LinearAlgebra
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (! Installing PD...rce install it.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Building and testing PDL-LinearAlgebra-0.37 ... FAIL
```

**Comment by mohawk2** [comment]
Thanks for the report!

I've transferred this issue to the correct repository for the distribution. I excerpt a line from your `build.log`:

```
C:/Strawberry/c/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: pp-__Nccharpol.o:pp-__Nccharpol.c:(.text+0xf26): undefined reference to `zgemm_'
```

I believe the problem here is that you don't have LAPACK installed, and/or findable, on your machine. Can you try installing the "PDL edition" of Strawberry, and try with that? I believe it does in fact have LAPACK with it.

Also, this distro is supposed to detect the absence of LAPACK, but that doesn't seem to have worked here. Sorry about that.

**Comment by offtob** [comment]
I have tried installing Math::Lapack, the install fails. So, it seems to 
be basic problem.

cpanm -i Math::Lapack
--> Working on Math::Lapack
Fetching 
http://www.cpan.org/authors/id/R/RU/RUISTEVE/Math-Lapack-0.002.tar.gz ... OK
cpanm : ! Configure failed for Math-Lapack-0.002. See 
E:\Shahriar\.cpanm\work\1684635455.39932\build.log for details.
At line:1 char:1
+ cpanm -i Math::Lapack
+ ~~~~~~~~~~~~~~~~~~~~~
     + CategoryInfo          : NotSpecified: (! Configure fai...og for 
details.:String) [], RemoteException
     + FullyQualifiedErrorId : NativeCommandError

Configuring Math-Lapack-0.002 ... N/A

**Comment by mohawk2** [comment]
The problem is that you don't have LAPACK installed.
